package db

import (
	model "predmer-api/models"
)

func NewMaterijal() map[int]*model.WingMaterijal {
	return map[int]*model.WingMaterijal{
		0: &model.WingMaterijal{
			Id:                1,
			Naziv:             "Glet masa-gletokol",
			Opis:              "Glet masa-gletokol",
			Obracun:           "Obračun po kilogrammu",
			Proizvodjac:       "maxima",
			OsobineNamena:     "GLETOLIN G je pastozna masa na bazi akrilata, namenjena za no gletovanje unutrašnjih, cvrsto malterisanih zidnih površina, kao i gips kartonskih ploca. GLETOLIN G odlikuje izuzetna belina, lakoca nanošenja i obradivost. Izravnane površine, koje su potpuno suve, mogu se bojiti svim vrstama disperzionih boja.",
			NacinRada:         "GLETOLIN G je pripremljen za ugradnju. Zidne površine moraju biti nosivo sposobne, ocišcene od prašine, masti i drugih necistoca. Pre nanošenja GLETOLIN-a G, površine grundirati odgovarajucom MAXIKRIL podlogom, u zavisnosti od stanja površine. GLETOLIN G nanositi na zidne površine pomocu celicne gletarice ili nerajucom farbarskom lopaticom.\nMože se nanositi i mašinski, pri cemu ga treba razrediti sa malo vode. Nakon sušenja, svaki sloj nanosa treba dobro izbrusiti brusnim papirom. Vreme sušenja, pre nanošenja narednog sloja, odnosno brušenja, pri optimalnim uslovima, je min. 12 casova. Maksimalna preporucena ukupna debljina sloja je do 3mm. Posle upotrebe, alat odmah oprati vodom",
			JedinicaPotrosnje: "kg/m², u zavisnosti od hrapavosti podloge",
			Potrosnja:         2.0,
			RokUpotrebe:       "12 meseci od datuma proizvodnje istaknutog na ambalaži. Cuvati\nu originalnoj, dobro zatvorenoj i neoštecenoj ambalaži, pri temperaturi od +5°C do +25\"",
			Jedinica:          "kg",
			Pakovanje:         25,
			Cena:              0.13,
			Slug:              "glet_masa_gletokol",
		},
		1: &model.WingMaterijal{
			Id:                2,
			Naziv:             "Masa za španski zid",
			Opis:              "Masa za španski zid",
			Obracun:           "Obračun po kilogrammu",
			Proizvodjac:       "evrojug",
			OsobineNamena:     " Španski zid je namenjen za dekorativnu zaštitu unutrašnjih zidova. Izrađen je od mineralnih agregata i hidrauličnih veziva aditiva. Španski zid se proizvodi u dve veličine zrna: 0mm i 1mm.\"",
			NacinRada:         "Masa se meša sa vodom u odnosu 1:3 (3 dela mase i 1 deo vode) ručno ili mešalicom. Zamešana masa treba da odstoji 10-25 minuta, zatim ponovo promeša i nanosi. Španski zid se nanosi na unutrašnje zidove koji su suvi, čisti i bez labavih delova i impregnirani Akrilnom emulzijom podloga. Masa se nanosi u jednom sloju metalnom gletaricom, a za krajnji izgled mogu se upotrebiti različiti valjci, pluta, stiropor, plastična gletarica itd.",
			JedinicaPotrosnje: "m2/kg",
			Potrosnja:         2,
			RokUpotrebe:       "12 meseci od datuma proizvodnje istaknutog na ambalaži. Cuvati u originalnoj, dobro zatvorenoj i neoštecenoj ambalaži, pri temperaturi od +5°C do +25\"",
			Jedinica:          "kg",
			Pakovanje:         25,
			Cena:              0.19,
			Slug:              "masa_za_spanski_zid",
		},
		2: &model.WingMaterijal{
			Id:                3,
			Naziv:             "Bavalit fasada",
			Opis:              "Bavalit fasada",
			Obracun:           "Obračun po kilogramu",
			Proizvodjac:       "granit pescar",
			OsobineNamena:     "Bavalit fasada u prahu izrađena na bazi najkvalitetnijih polimera, odgovarajućih punila i aditiva.   Upotrebljava se za zaštitu fasade ili za dekorativnu obradu unutrašnjih prostorija, a nanosi se na razne podloge od betona, krečnog i produžnog maltera. \"",
			NacinRada:         "Priprema se za nanošenje tako što se sadržaj vreće od 40 kg suve komponente izmeša u mešalici za beton uz dodatak jedne kante emulzije od 1,2 kg i 10 litara vode, do potpune homogenizacije. Pripremljena masa pogodne gustoće nanosi se na pripremljenu podlogu pomoću metalne gletelice, zatim se zariba pomocu tvrdog stiropora. ",
			JedinicaPotrosnje: "kg/m² Utrošak zavisi od načina nanošenja i podloge.",
			Potrosnja:         3.5,
			RokUpotrebe:       "Rok upotrebe je 12 meseci u orginalnoj ambalaži. ",
			Jedinica:          "kg",
			Pakovanje:         25,
			Cena:              0.165,
			Slug:              "bavalit_fasada",
		},
		3: &model.WingMaterijal{
			Id:                4,
			Naziv:             "Fasada hirofa",
			Opis:              "Fasada hirofa",
			Obracun:           "Obračun po kilogrammu",
			Proizvodjac:       "fasada",
			OsobineNamena:     "Hirofa je tankoslojni mineralni krečno-cementni malter namenjen za ukrašavanje spoljašnjih zidnih površina, granulacije 1,0 mm. Odgovarajuće podloge su sve površine od krečnih, cementnih i cementno-krečnih maltera (stare najmanje mesec dana), cementno-vlaknaste ploče, betonske površine (stare najmanje 3 meseca) i sl. Hirofa se proizvodi u beloj boj i tonira se po Fasada ton karti",
			NacinRada:         "Podloga na koju se nanosi mineralni dekorativni malter mora biti čvrsta i grubo zaribana, bez prašine, slabo vezanih delova, soli i masnih mrlja. Uljane boje i lakove potrebno je ukloniti sa zida pre nanošenja Hirofe. Ako je površina suva potrebno ju je pokvasiti vodom da bi bila vlažna i ohlađena, što omogućava bolje vezivanje i prijanjanje uz podlogu.  Hirofa se meša električnim mikserom sa  oko 25% vode (na džak od 25 kg dodati oko 6 litara vode), do homogenizacije. Masu ostaviti da odstoji 10 min, zatim još jednom promešati i po potrebi dodati malo vode za podešavanje odgovarajuće konzistencije. Malter nanositi pomoću „ježa“ ili kompresorskim pištoljem prilagođenim špricanju Hirofe, pri čemu se dobija struktura kao prskana fasada. Malter je potrebno nanositi brzo, ravnomerno i bez prekida na kontinualnoj zidnoj površini. Preporučuje se nanošenje u više tanjih nanosa, kako se malter ne bi slivao i ispucao. Između dva nanosa treba sačekati da malter površinski osuši. Nakon nanošenja potrebno je u periodu od nekoliko dana orošavati površinu. Time se sprečava naglo sušenje i omogućava postepeno vezivanje, čvrstoća i otpornost.  Temperatura vazduha i podloge prilikom ugradnje treba da bude od +5°C do +30°C i relativna vlažnost vazduha ispod 65%. Ne raditi na vetru ili promaji, fasadu zaštititi od direktnih sunčevih zraka. Odmah nakon upotrebe alat oprati vodom. Očvrsle ostatke mehanički ukloniti. Hirofa se proizvodi u beloj boj, tonira se po Fasada ton karti. Za poručene količine manje od 600 kg, toniranje vrši majstor na licu mesta. Pri tome treba voditi računa da se dobro promeša u praškastom stanju da ne bi došlo do šarenila na fasadi.  Preporučujemo upotrebu Hirofe u beloj boje i naknadno bojenje mineralnog maltera disperzivnim akrilnim ili silikatnim bojama u željenoj nijansi, prema Fasada ton karti. Bojenje vršiti nakon 28 dana od nanošenja Hirofe.     ",
			JedinicaPotrosnje: "kg/m²",
			Potrosnja:         3.5,
			RokUpotrebe:       "Rok trajanja do 6 meseci u originalnom i neoštećenom pakovanju. Proizvod čuvati u originalnoj, zatvorenoj ambalaži na suvom mestu, zaštićenom od vlage.",
			Jedinica:          "kg",
			Pakovanje:         25,
			Cena:              0.15,
			Slug:              "fasada_hirofa",
		},
		4: &model.WingMaterijal{
			Id:                5,
			Naziv:             "Lepak za siporeks blokove",
			Opis:              "Lepak za siporeks blokove",
			Obracun:           "Obračun po kilogrammu",
			Proizvodjac:       "Knauf",
			OsobineNamena:     "abrički pripremljen praškasti malter za tankoslojno zidanje gasbeton blokovima. Cementni malter namenjen za zidanje gasbeton blokovima. Namenjen za tankoslojno nanošenje. Za zidanje spoljašnjih, pregradnih zidova i stubova od gasbeton blokova. ",
			NacinRada:         "Površina blokova na koju se malter nanosi mora biti suva, otprašena, odmašćena, nosiva, ravna i bez ostataka koji umanjuju prionljivost maltera. Spoljašnje površine izložene atmosferskim uticajima, tokom izvođenja i sušenja materijala, zaštiti od padavina i direktnog uticaja sunca. Sadržaj vreće (25 kg) dodati u ca. 6,5 l čiste vode i mešati dok se materijal potpuno ne homogenizuje. Nakon toga pripremljeni materijal ostaviti 10 minuta da odstoji i još jednom promešati. Ovako pripremljen materijal je spreman za upotrebu. Konzistenciju po potrebi podesiti dodavanjem vode ili praha. Otvoreno vreme za malter u kofi je ca. 2 časa. Alat odmah nakon upotrebe očistiti sa vodom. Malter se nanosi zupčastom gletericom. Zidanje izvesti u skladu sa tehničkim propisom za zidane konstrukcije kao i prema tehničkim uputstvima proizvođača gasbeton blokova. Maksimalna debljina nanošenja je 5 mm. Sve fuge se moraju u potpunosti ispuniti malterom. Višak maltera iz fuga odstraniti zidarskom mistrijom. ",
			JedinicaPotrosnje: "kg/m²",
			Potrosnja:         5,
			RokUpotrebe:       "Materijal ne treba nanositi pri temperaturama vazduha i podloge ispod +5°C i višim od 25°C. Sveže naneseni malter zaštiti od promaje, prebrzog sušenja i mraza.",
			Jedinica:          "kg",
			Pakovanje:         25,
			Cena:              0.095,
			Slug:              "lepak_za_siporeks blokove",
		},
		5: &model.WingMaterijal{
			Id:                6,
			Naziv:             "Lepak za keramičke pločice Pk-111",
			Opis:              "Lepak za keramičke pločice Pk-111",
			Obracun:           "Obračun po kilogrammu",
			Proizvodjac:       "Knauf",
			OsobineNamena:     "abrički pripremljen praškasti malter za tankoslojno zidanje gasbeton blokovima. Cementni malter namenjen za zidanje gasbeton blokovima. Namenjen za tankoslojno nanošenje. Za zidanje spoljašnjih, pregradnih zidova i stubova od gasbeton blokova. ",
			NacinRada:         "Površina blokova na koju se malter nanosi mora biti suva, otprašena, odmašćena, nosiva, ravna i bez ostataka koji umanjuju prionljivost maltera. Spoljašnje površine izložene atmosferskim uticajima, tokom izvođenja i sušenja materijala, zaštiti od padavina i direktnog uticaja sunca. Sadržaj vreće (25 kg) dodati u ca. 6,5 l čiste vode i mešati dok se materijal potpuno ne homogenizuje. Nakon toga pripremljeni materijal ostaviti 10 minuta da odstoji i još jednom promešati. Ovako pripremljen materijal je spreman za upotrebu. Konzistenciju po potrebi podesiti dodavanjem vode ili praha. Otvoreno vreme za malter u kofi je ca. 2 časa. Alat odmah nakon upotrebe očistiti sa vodom. Malter se nanosi zupčastom gletericom. Zidanje izvesti u skladu sa tehničkim propisom za zidane konstrukcije kao i prema tehničkim uputstvima proizvođača gasbeton blokova. Maksimalna debljina nanošenja je 5 mm. Sve fuge se moraju u potpunosti ispuniti malterom. Višak maltera iz fuga odstraniti zidarskom mistrijom. ",
			JedinicaPotrosnje: "kg/m²",
			Potrosnja:         5,
			RokUpotrebe:       "Materijal ne treba nanositi pri temperaturama vazduha i podloge ispod +5°C i višim od 25°C. Sveže naneseni malter zaštiti od promaje, prebrzog sušenja i mraza.",
			Jedinica:          "kg",
			Pakovanje:         25,
			Cena:              0.1,
			Slug:              "lepak_za_keramicke_plocice_pk_111",
		},
		6: &model.WingMaterijal{
			Id:                7,
			Naziv:             "Lepak za stiropor",
			Opis:              "Lepak za stiropor",
			Obracun:           "Obračun po kilogrammu",
			Proizvodjac:       "zorka",
			OsobineNamena:     "Koristi se za lepljenje I armiranje termoizolacionih ploca, kao I zalepljenje elemenata od stiropora I stirodura.",
			NacinRada:         "Lepak za stiropor priprema se sa vodom. U masu se dodaje 35-40% vode uz mesanje do potpune homogenizacije. Masa je potom spremna za upotrebu. Nanosi se gletericom na navlazenu podlogu. Pripremljenu masu upotrebiti u roku od 1 casa.",
			JedinicaPotrosnje: "kg/m²",
			Potrosnja:         10,
			RokUpotrebe:       "12 meseci u suvim prostorijama.",
			Jedinica:          "kg",
			Pakovanje:         25,
			Cena:              0.11,
			Slug:              "lepak_za_stiropor",
		},
		7: &model.WingMaterijal{
			Id:                8,
			Naziv:             "Lepak za kamenu vunu",
			Opis:              "Lepak za kamenu vunu",
			Obracun:           "Obračun po kilogrammu",
			Proizvodjac:       "maxima",
			OsobineNamena:     "STIROMOL Elastic je jednokomponentni, visokoelastični, suvi tip građevinskog lepka, izrađen od hidrauličnih i sintetičkih veziva, uz dodatak specijalnih aditiva. Namenjen je za lepljenje i armiranje termoizolacionih ploča: stiropora, termosila, stirodura i kamene vune, na sve vrste mineralnih podloga.",
			NacinRada:         "STIROMOL Elastic od 25kg dodati na 6-6.5l vode i mešati do stvaranja homogene mase bez grudvica. Sačekati 10 minuta, pa ponovo intenzivno izmešati. Ovako pripremljena masa spremna je za ugradnju i mora se utrošiti u roku od 2 časa. STIROMOL Elastic nanositi na termoizolacione ploče uz ivicu i u 3-6 tačaka po sredini ploče (pokrivnost lepkom min. 40%). Na ploče kamene vune naneti lepak celom površinom, koristeći nazubljenu gletaricu. Ploče pritiskanjem lepiti na čvrstu i čistu podlogu. Na zalepljene termoizolacione ploče, nakon 2-3 dana, preporučujemo tiplovanje (6 kom/m²). Postavljanje armaturne mrežice vršiti utiskivanjem u sloj nanetog STIROMOL Elastic-a, u debljini od 2-3mm, sa preklopom od 10cm, a zatim celokupnu površinu izravnati STIROMOL Elastic-om. Ukupna debljina nanetog STIROMOL-a Elastic treba da bude min. 4mm.",
			JedinicaPotrosnje: "kg/m²",
			Potrosnja:         5,
			RokUpotrebe:       "12 meseci od datuma proizvodnje istaknutog na ambalaži. Čuvati u zatvorenoj i neoštećenoj ambalaži, u suvoj i provetrenoj prostoriji",
			Jedinica:          "kg",
			Pakovanje:         25,
			Cena:              0.14,
			Slug:              "lepak_za_kamenu_vunu",
		},
		8: &model.WingMaterijal{
			Id:                9,
			Naziv:             "Lepak za kamen vajt (beli)",
			Opis:              "Lepak za kamen vajt (beli)",
			Obracun:           "Obračun po kilogrammu",
			Proizvodjac:       "rofix",
			OsobineNamena:     "Brzovezujući, beli, fleksibilni, tankoslojni lepak za visoke zahteve prema normi EN 12004 za postavljanje mermernih ploča i ploča od prirodnog kamena kao i drugih prirodnih ploča osetljivih na obojanje, na podu i zidu. Podesno u unutrašnjim i spoljašnjim područjima za estrih i podno grejanje. Za podove pod toplotnim opterećenjem, npr. na terasama, balkonima i na grejanim estrisima te u području saniranja kod lepljenja pločica na stare keramičke površine. Posebno podesno za svetle ploče i pločice. Zbog brzog vezanja potrebne vode za zamešavanje materijala može se smanjiti promena boje na površini svetlih ploča.",
			NacinRada:         "RÖFIX Lepak za keramiku naneti glatkom stranom zupčastog gletera na podlogu i sa nazubljenom stranom gletera pročešljati po mogućnosti u jednom smeru. Lepak naneti samo na onoliku površinu na koju je za vreme trajanja otvorenog vremena materijala moguće ugraditi obloge. Ukoliko se zahteva postavljanje pločica bez šupljina ispod pločica (u trajno vlažnim područjima), potrebno je raditi po metodi \"Floating- Buttering\". Lepak je podesan za obloge do veličine formata 60x60 cm. Na poleđinu obloga formata > 0,25 m² prethodno je potrebno ugraditi masu za poboljšanje prionjivosti. Ne koristiti materijal iz već otvorenih, starih pakovanja i ne mešati sa novim materijalom. Pločice se pomicanjem postavljaju u lepak, a njihov položaj se može ispraviti u propisanom roku za vreme postavljanja. ",
			JedinicaPotrosnje: "kg/m² zupčastim gleterom od 8 mm",
			Potrosnja:         3,
			RokUpotrebe:       "Skladištiti na suvom mestu (ako je moguće na drvenim paletama). Datum proizvodnje odštampan na vreći. Rok upotrebe najmanje 12 meseci prema direktivi 1907/2006/EZ na 20 °C, 65 % r.v.v. ",
			Jedinica:          "kg",
			Pakovanje:         25,
			Cena:              0.44,
			Slug:              "lepak_za_kamen_vajt_beli",
		},
		9: &model.WingMaterijal{
			Id:                10,
			Naziv:             "Lepak za keramiku Pk-116",
			Opis:              "Lepak za keramiku Pk-116",
			Obracun:           "Obračun po kilogrammu",
			Proizvodjac:       "cere4sit",
			OsobineNamena:     "Ceresit CM 16 fleksibilni lepak je namenjen za postavljanje svih vrsta mozaika uključujući staklo i keramiku, mermer, granit, peščar, travertin, mešavinu  svetlih krečnjaka i drugih krupnozrnastih kamenih ploča. Takođe je pogodan za postavljanje keramičkih i gres pločica (sa upijanjem manjim od 0,5%), glaziranih keramičkih pločica i terakote. Uzorkovanje se preporučuje svaki put pre postavljanja pločica kako bi se osiguralo da lepak ne uzrokuje promenu boje na pločicama. Svojstva lepka omogućavaju postavljanje pločica na gipsanim tablama, sistemima za podno grejanje, suvim košuljicama, gipsu, zasićenom betonu i  vodonepropusnim slojevima (osim crne bitumenske hidroizolacije). Može se primeniti u vlažnim prostorima kao što su kupatila, bazeni, na terasama, balkonima sa odgovarajućim dilatacionim spojevima, stepeništima, podnom grejanju, fasadama, OSB pločama i na postojećim keramičkim oblogama. Pogodan je za mesta sa teškim saobraćajem i visokim opterećenjima kao što su komunikacione zone, koridori, škole, supermarketi, prodavnice, restorani itd. CM 16 fleksibilni lepak ima visoku i snažnu moć prianjanja. Sušenje i vezivanje se odvija bez skupljanja. Za druge tipove pločica i druge podloge ili veća opterećenja preporučuju se odgovarajuci Ceresit lepkovi. ",
			NacinRada:         "Ceresit CM 16 može da se primeni na kompaktne, čvrste i nosive podloge bez ikakvih supstanci koje smanjuju prianjanje (masti, prašine, bitumenski premazi, ostaci crne izolacije, premazi boja i sl.). Betoni (najmanje 28 dana stari, sa ostatkom vlage ≤ 2%), cementne košuljice i malteri na bazi cementa i kreča (najmanje 28 dana stari sa ostatkom vlage ≤ 1,5%), anhidrit (ostatak vlage ≤ 0,5%) i gips malteri (ostatak vlage ≤1%) treba da budu mehanički ohrapavljene i očišćeni od prašine, a zatim premazani sa prajmerom CT 17 ili CN 94. Podloge ne smeju biti mokre. Sve postojeće nečistoće, labave slojeve i slabije premaze boja bi trebalo mehanički ukloniti. Upijajuće podloge treba premazati sa Ceresit CT 17 i ostaviti da se suše najmanje 2 sata. Neravnine do 5 mm mogu biti popunjene dan ranije pomoću CX5. U slučaju većih neravnina i  udubljenja koristiti Ceresit samonivelišuce mase (npr. CN69) odnosno brzovezujuću košuljicu CN 85. Ivericu i OSB treba ošmirglati i premazati sa CN94. Postojeće pločice treba očistiti, odmastiti i premazati sa CN94.   Sipajte sadržaj pakovanja u posudu sa precizno izmerenom količinom čiste i hladne vode i mešati korišćenjem bušilice ili miksera dok se ne dobije homogena masa bez grudvica. Ostavite 5 minuta a zatim ponovo promešati smešu. Nanesite lepak sa odgovarajućom nazubljenom gletericom. Za unutrašnju zidnu upotrebu pokrivenost kontaktne površine lepkom na poleđini upojne pločice mora biti najmanje 70%. Metod kontaktnog lepljenja se preporučuje za podne i veće pločice (pločice čija je jedna ivica veća od 30 cm) kao i za spoljašnju  potrebu (dodatno se može naneti tanak sloj lepka na zadnjoj strani pločice čime se postiže kontaktna površina veća od 95%). Postavljati pločice samo u periodu otvorenog vremena za lepljenje. Svež višak lepka se može ukloniti sa vodom. Očvrsli materijal se može ukloniti samo mehanički. Fugovanje se izvodi kada je lepak potpuno suv i koriste se Ceresit materijali iz CE grupe. Ne postavljati pločice bez spojnica! Poštovati širinu spojnica u zavisnosti od veličine pločica, uslova korišćenja i preporuke proizvođača pločica. Dilatacije, spojnice u uglovima, zid-pod, zid-zid i oko sanitarija treba popuniti sa Ceresit trajno elastičnim zaptivnim masama",
			JedinicaPotrosnje: "kg/m²",
			Potrosnja:         5,
			RokUpotrebe:       "Radove izvoditi u suvim uslovima pri temperaturama od +5°C do +25°C. Svi podaci su dobijeni pri temperaturi od 23°C i relativnoj vlažnosti od 50 %. Različiti uslovi mogu izazvati usporavanje ili ubrzavanje očvršćavanja. U slučaju polaganja pločica od kamena koji je podležan promenama boje obavezno je uzorkovanje kako bi se proverilo da li lepak izaziva promene na pločicama. Pored preporuka datih u ovom dokumentu, radovi bi trebalo da budu izvedeni u skladu sa građevinskim standardima i pravilima zaštite na radu. U slučaju bilo kakvih nedoumica, kontaktirajte tehničku podršku ili sprovedite proceduru uzorkovanja. Sadrži cement. Sa vlagom reaguje jako alkalno, tako da treba zaštititi kožu i oči. U slučaju kontakta sa očima,isprati oči vodom i obavezno se obratiti lekaru. ",
			Jedinica:          "kg",
			Pakovanje:         25,
			Cena:              0.24,
			Slug:              "lepak_za_keramiku_pk_116",
		},
		10: &model.WingMaterijal{
			Id:                11,
			Naziv:             "Glet masa spoljna",
			Opis:              "Glet masa spoljna",
			Obracun:           "Obračun po kilogrammu",
			Proizvodjac:       "maxima",
			OsobineNamena:     "GLETOLIN S je praškasta masa na osnovi belog cementa, punila i specijalnih aditiva, namenjena za gletovanje betonskih i cvrsto malterisanih spoljašnjih i unutrašnjih zidnih površina. GLETOLIN S odlikuje izuzetna belina, lakoca nanošenja i obradivost. Izravnane površine, koje su potpuno suve, mogu se bojiti svim vrstama disperzionih boja u enterijerima, odnosno fasadnim bojama kod fasadnih površina.",
			NacinRada:         "LETOLIN S od 25kg dodati na 9l vode i mešati do stvaranja homogene mase bez grudvica. Sacekati 15 minuta, pa ponovo intenzivno izmešati. Ovako pripremljena masa spremna je za ugradnju i mora se utrošiti u roku od 2 casa. Zidne površine moraju biti nosivo sposobne, ocišcene od prašine, masti i drugih necistoca. Pre nanošenja GLETOLIN-a S, površine grundirati odgovarajucom MAXIKRIL podlogom, u zavisnosti od stanja površine. Masa se obicno nanosi u dva sloja, rucno, nerajucom gletaricom. Vreme sušenja, pre nanošenja narednog sloja, odnosno brušenja, pri optimalnim uslovima je min. 24 casa. Ukupna debljina dvoslojnog nanosa ne sme da iznosi više od 3mm. Ovako gletovane površine mogu se bojiti nakon 14 dana. Posle upotrebe, alat odmah oprati vodom. Radna temperatura: Optimalna radna temperatura je od +10°C do +30°C. Ne sme se koristiti ispod +5°C, kao i po jakom suncu, vetru, magli i kiši. Sveže nanete površine, u optimalnim uslovima, zaštititi od atmosferskih uticaja najmanje 24 casa.",
			JedinicaPotrosnje: "kg/m², u zavisnosti od hrapavosti podloge.",
			Potrosnja:         1.5,
			RokUpotrebe:       "meseci od datuma proizvodnje istaknutog na ambalaži.Cuvati u zatvorenoj i neoštecenoj ambalaži, u suvoj i provetrenoj prostoriji.",
			Jedinica:          "kg",
			Pakovanje:         25,
			Cena:              0.24,
			Slug:              "glet_masa_spoljna",
		},
		11: &model.WingMaterijal{
			Id:                12,
			Naziv:             "Mašinski malter krečno-cementni",
			Opis:              "Mašinski malter krečno-cementni",
			Obracun:           "Obračun po kilogrammu",
			Proizvodjac:       "maxima",
			OsobineNamena:     "MAXIMAL je gotovi krečnocementni malter, namenjen za mašinsko i ručno malterisanje svih nosivo sposobnih unutrašnjih zidnih površina. Može se koristiti kod svih vrsta zidova od cigle, opeke, gasbetonskih elemenata, betona i prirodnog kamena.",
			NacinRada:         "Površine moraju biti: suve, očišćene od prašine, masti i drugih nečistoća kao i slabo vezanih delova. Veće neravnine kao i rupe i šliceve od instalacija potrebno je prethodno ispuniti. Kod zidova koji su izrađeni ciglom, gde su fugne doboke i široke, iste je potrebno prethodno ispuniti pre malterisanja. Ovako pripremljene površine grundirati. Prilikom grundiranja glatkih površina, pre svega savetujemo upotrebu MAXIMAL Špric-a; druga preporuka je akrilni vezivni most MAXIKRIL Contact. Jako upojne površine grundirati MAXIKRIL Concentrate podlogom. Malter nanositi mašinski i odmah nakon toga grubo poravnati aluminijumskom „H“ letvom. Posle delimičnog sušenja vrši se odstranjivanje viška materijala. Malter se „otvara“ aluminijumskom „T“ letvom ili rešetkastim strugačem (rajbnom). Površina posle ove obrade ostaje gruba. Nakon „otvaranja“ površina se kvasi vodom i perdaši sunđerastom hoblom, čime se dobija fini konačni izgled. Minimalna debljina sloja je 1.5cm. Na neravnim površinama kod kojih je potrebno nanositi malter u debljem sloju, ponovo naneti malter sa pravljenjem pauze ali dok prethodni sloj još nije vezao. ",
			JedinicaPotrosnje: "kg/m² za 10mm debljine za ravne površine.",
			Potrosnja:         14,
			RokUpotrebe:       "",
			Jedinica:          "kg",
			Pakovanje:         30,
			Cena:              0.071,
			Slug:              "masinski_malter_krecno_cementni",
		},
		12: &model.WingMaterijal{
			Id:                13,
			Naziv:             "Glet masa",
			Opis:              "Glet masa",
			Obracun:           "Obračun po kilogrammu",
			Proizvodjac:       "",
			OsobineNamena:     "GLETOLIN G je pastozna masa na bazi akrilata, namenjena za no gletovanje unutrašnjih, cvrsto malterisanih zidnih površina, kao i gips kartonskih ploca. GLETOLIN G odlikuje izuzetna belina, lakoca nanošenja i obradivost. Izravnane površine, koje su potpuno suve, mogu se bojiti svim vrstama disperzionih boja.",
			NacinRada:         " GLETOLIN G je pripremljen za ugradnju. Zidne površine moraju biti nosivo sposobne, ocišcene od prašine, masti i drugih necistoca. Pre nanošenja GLETOLIN-a G, površine grundirati odgovarajucom MAXIKRIL podlogom, u zavisnosti od stanja površine. GLETOLIN G nanositi na zidne površine pomocu celicne gletarice ili nerajucom farbarskom lopaticom. Može se nanositi i mašinski, pri cemu ga treba razrediti sa malo vode. Nakon sušenja, svaki sloj nanosa treba dobro izbrusiti brusnim papirom. Vreme sušenja, pre nanošenja narednog sloja, odnosno brušenja, pri optimalnim uslovima, je min. 12 casova. Maksimalna preporucena ukupna debljina sloja je do 3mm. Posle upotrebe, alat odmah oprati vodom",
			JedinicaPotrosnje: "kg/m², u zavisnosti od hrapavosti podloge",
			Potrosnja:         1.5,
			RokUpotrebe:       "12 meseci od datuma proizvodnje istaknutog na ambalaži. Cuvati u originalnoj, dobro zatvorenoj i neoštecenoj ambalaži, pri temperaturi od +5°C do +25",
			Jedinica:          "kg",
			Pakovanje:         5 / 1,
			Cena:              0.18,
			Slug:              "glet_masa",
		},
		13: &model.WingMaterijal{
			Id:                14,
			Naziv:             "Građevinski lepak",
			Opis:              "Građevinski lepak",
			Obracun:           "Obračun po kilogrammu",
			Proizvodjac:       "",
			OsobineNamena:     "Lepak za lepljenje termoizolacionih ploča od belog EPS-a na čvrste mineralne površine.",
			NacinRada:         "Podloge i glatke maltere impregnirati EFFECTA Grund podlogom za fasadni malter ili Linea podlogom (u razređenju 1 deo Linea podloge i 4 dela vode). Effecta basic lepak za EPS umešati sa cca 5,5 l čiste vode ručno ili mikserom. Smeša mora biti homogena, bez grudvica, pogodna za nanošenje. Vreme obrade: oko 90-100 minuta. Nanosi se nerđajućom gletericom. Odmah nakon primene dobro oprati sav alat vodom.",
			JedinicaPotrosnje: "kg/m² za lepljenje stiropor ploča",
			Potrosnja:         4.5,
			RokUpotrebe:       "U suvom prostoru +5°C do +25°C",
			Jedinica:          "kg",
			Pakovanje:         5 / 1,
			Cena:              0.18,
			Slug:              "gradjevinski_lepak",
		},
		14: &model.WingMaterijal{
			Id:                15,
			Naziv:             "Spoljni mašinski malter-cementni",
			Opis:              "Spoljni mašinski malter-cementni",
			Obracun:           "Obračun po kilogrammu",
			Proizvodjac:       "maxima",
			OsobineNamena:     "MAXIMAL S je gotovi cementno-krecni malter, namenjen za mašinsko i rucno malterisanje svih nosivo sposobnih spoljašnjih i unutrašnjih zidnih površina. Može se koristiti kod svih vrsta zidova od cigle, opeke, gasbetonskih elemenata, betona i prirodnog kamena.",
			NacinRada:         "Površine moraju biti suve, ocišcene od prašine, masti i drugih necistoca kao i slabo vezanih delova. Vece neravnine kao i rupe i šliceve od instalacija potrebno je prethodno ispuniti. Kod zidova koji su izraeni ciglom, gde su fugne doboke i široke, iste je potrebno prethodno ispuniti pre malterisanja. Ovako pripremljene površine gundirati. Prilikom grundiranja glatkih površina, pre svega savetujemo upotrebu MAXIMAL Šrpic-a; druga preporuka je akrilni vezivni most MAXIKRIL Contact. Jako upojne površine grundirati MAXIKRIL Concentrate podlogom. Malter nanositi mašinski i odmah nakon toga grubo poravnati aluminijumskom „H“ letvom. Posle delimicnog sušenja vrši se odstranjivanje viška materijala. Malter se „otvara“ aluminijumskom „T“ letvom ili rešetkastim strugacem (rajbnom). Površina posle ove obrade ostaje gruba. Nakon „otvaranja“ površina se kvasi vodom i perdaši sunerastom hoblom, cime se dobija ni konacni izgled. Minimalna debljina sloja je 1.5cm. Na neravnim površinama kod kojih je potrebno nanositi malter u debljem sloju, ponovo naneti malter sa pravljenjem pauze ali dok prethodni sloj još nije vezao.",
			JedinicaPotrosnje: "kg/m² za 10mm debljine za ravne površine.",
			Potrosnja:         14,
			RokUpotrebe:       "6 meseci od datuma proizvodnje istaknutog na ambalaži. Cuvati u zatvorenoj i neoštecenoj ambalaži, u suvoj i provetrenoj prostoriji. ",
			Jedinica:          "kg",
			Pakovanje:         30,
			Cena:              0.085,
			Slug:              "spoljni_masinski_malter_cementni",
		},
		15: &model.WingMaterijal{
			Id:                16,
			Naziv:             "PK POL",
			Opis:              "PK POL",
			Obracun:           "Obračun po kilogrammu",
			Proizvodjac:       "jupol",
			OsobineNamena:     "Koristi se za unutrašnju upotrebu, poseduje odliènu pokrivnu moæ i paropropusnost, otporna na suvo brisanje. Bez mirisa.Može se tonirati u željene nijanse.",
			NacinRada:         "Priprema smese se vrši dodavanjem 15-20% vode uz mešanje do potpune homogenizacije. Površina na koju se boja nanosi mora biti čvrsta, èista, suva i impregnirana podlogom. Nanošenje se vrši valjkom u dva sloja ili pomoæu kompresora. Drugi sloj se nanosi nakon potpunog sušenja prvog sloja.Potrošnja: 0,2-0,3 kg/m2 za dvoslojni premaz.",
			JedinicaPotrosnje: "kg/m2",
			Potrosnja:         0.3,
			RokUpotrebe:       "12 meseci u originalnoj ambalaži skladišteno na suvom mestu, zaštiæeno od sunèeve svetlosti i smrzavanja. Datum proizvodnje i pakovanja utisnut na ambalaži.",
			Jedinica:          "kg",
			Pakovanje:         25,
			Cena:              0.3,
			Slug:              "pk_pol",
		},
		16: &model.WingMaterijal{
			Id:                17,
			Naziv:             "PK DSP",
			Opis:              "PK DSP",
			Obracun:           "Obračun po kilogrammu",
			Proizvodjac:       "12 meseci od datuma proizvodnje istaknutog na ambalaži. Cuvati u originalnoj, dobro zatvorenoj i neoštecenoj ambalaži, pri temperaturi od +5°C do +25°C, zaštićeno od direktne sunčeve svetlosti.",
			OsobineNamena:     "JUPOL Plus je disperzivna boja namenjena za dekorativnu zaštitu zidova i plafona u stambenim i poslovnim zgradama, školama, vrtićima, bolnicama, domovima za starije i drugim objektima, ako za takvu zaštitu nije zahtevana upotreba perivih boja, odnosno boja otpornih na mokro brisanje. Primerene podloge su fini malteri svih vrsta, površine zaglađene masama za izravnavanje, reljefne papirne tapete, pa i gips kartonske i vlakneno cementne ploče, iverice, neomalterisan beton, i sl. Moguć je nanos i na dobro prihvaćene stare disperzijske premaze i dobro prihvaćene dekorativne meltere svih vrsta.    Boju odlikuje izuzetna belina, izuzetno nizak sadržaj lako isparljivih organskih materija. Ne sadrži teške metale. Jednostavna je za nanošenje i na raspolaganju je u velikom broju nijansi. Film boje je paropropustan i otporan na suvo brisanje. Prilikom brisanja mokrom krpom ili sunđerom smekša i ošteti se.    Ukoliko se koristi dekorativnu zaštitu zidnih i plafonskih površina, na kojima zbog visoke relativne vlažnosti vazduha postoji velika verovatnoća pojave kondenzacije i mogućnost za intenzivan razvoj različitih vrsta zidnih buđi (kuhinje, kupatila i drugi sanitarni prostori, perionice i sl.) preporučuje se da se u boju doda od 5 do 7,5 % (50 do 75 ml/l) JUBOCIDA.  ",
			NacinRada:         "Podloga treba da bude čvrsta, suva i čista – bez slabo vezanih delova, prašine, ostataka oplatnih ulja, masti i druge prljavštine. Boju pre upotrebe samo promešati, zatim je na konzistenciju primerenu tehnici i načinu nanašanja razrediti vodom (najviše 15 % za beli i pastelne nijanse, 10 % za intenzivnije nijanse). OPREZ! Pokrivnost boje razređivanjem se smanjuje!    Boju, koja nam je potrebna za premazivanje određene površine (ili još bolje: svih površina, koje bojimo u istoj nijansi), egalizovati u dovoljno velikoj posudi. Za velike površine, za koje na takav način tehnički nije moguće pripremiti dovoljne količine boje niti za jednoslojni nanos, u egalizacijskoj posudi izmešati najpre boju iz najmanje tri kante. Kad se upotrebi jedna trećina tako pripremljene boje, u posudu doliti novu boju i sa preostalom u posudi je dobro promešati, itd. Egalizacija bele boje iste proizvodne šarže, koju nismo razređivali, nije potrebna.    Bilo kakvo „popravljanje“ boje usred bojenja (dodavanje nijansirnih sredstva, razređivanje, i sl.) nije dozvoljeno. Količinu boje, koja je potrebna za bojenje pojedinih površina, izračunati ili oceniti iz površine tih površina i podataka o prosečnoj potrošnji. U specifičnim primerima potrošnju odrediti merenjem na dovoljno velikoj testnoj površini. Boju nanositi u dva sloja u razmaku 4 – 6 sati (T = +20 ºC, rel. vl. vazduha = 65 %), dugodlakim krznenim, odnosno tekstilnim valjkom (dužina dlaka 18 – 20 mm, upotrebljivo je prirodno ili veštačko krzno od različitih sintetičkih niti - poliamid, dralon, najlon, perlon ili poliester), farbarskom četkom primerenom za nanos disperzijskih zidnih boja ili špricanjem. Pojedinu zidnu površinu bojiti bez prekida od jednog do drugog krajnjeg ruba. Za standardno dugodlaki farbarski valjak ili pištolj za špricanje nedostupne površine (ćoškovi, uglovi, žlebovi, uske špalete i sl.) koristiti primerenu četku ili manji farbarski valjak i uvek ih obraditi prve.    Bojenje je moguće samo u primerenim vremenskim uslovima odnosno odgovarajućim mikroklimatskim uslovima: temperatura vazduha i zidne podloge ne sme da bude niža od +5 ºC i ne viša od +35 ºC, relativna vlažnost vazduha ne viša od 80 %. +   Novougrađene maltere i mase za izravnavanje u normalnim uslovima (T = +20 ºC, rel. vl. vazduha = 65 %) sušiti, odnosno dozrevati najmanje 1 dan za svaki mm debljine. Za betonske podloge vreme sušenja je minimalno jedan mesec. Sa već prebojenih površina odstraniti sve, u vodi lako i brzo rastvorive nanose boja, nanose uljanih boja, lakova i emajla. Pre bojenja obavezno dezinfikovati površine zaražene zidnim buđima.    Ukoliko je neophodno (visoko upojne podloge, glet mase na bazi kreča...) preporučujemo nanos temeljnog premaza - vodom razređenu AKRIL EMULZIJU (AKRIL EMULZIJA : voda = 1 : 3), dok za zahtevnije i manje kvalitetne površine (manje kvalitetne obloge od gips kartonskih ploča, gips meltere, krečnocementnih ploča, iverice i neomalterisane betonske podloge) vodom razređen JUKOL (JUKOL : voda = 1 : 1). Temeljni premaz naneti farbarskom ili zidarskom četkom ili dugodlakim krznenim ili tekstilnim farbarskim valjkom, a moguće je i špricanjem. Bojenje nastaviti, u normalnim  uslovima (T = +20 ºC, rel. vl. vazduha = 65 %), 6 h (AKRIL EMULZIJA) odnosno 12 h (JUKOL) od nanosa temeljnog premaza. Kao temeljni premaz za upojne gletovane podloge i stare disperzijske premaze, preporučuje se i do 30% vodom razređen JUPOL Plus, s tim što je nakon ovoga obavezan dvoslojni nanos do 15% razređene boje.     Prilikom obnavljajućeg bojenja i pre nanošenja boje na podloge zaglađene disperzisjkim masama za izravnavanje, temeljni premaz obično nije potreban.  ",
			JedinicaPotrosnje: "l/m2 u zavisnosti od vrste i hrapavosti podloge (dvoslojni nanos)",
			Potrosnja:         0.15,
			RokUpotrebe:       "U suvom prostoru +5°C do +25°C",
			Jedinica:          "kg",
			Pakovanje:         8,
			Cena:              0.38,
			Slug:              "pk_dsp",
		},
		17: &model.WingMaterijal{
			Id:                18,
			Naziv:             "Mašinski malter rinfuz",
			Opis:              "Mašinski malter rinfuz",
			Obracun:           "Obračun po kilogrammu",
			Proizvodjac:       "",
			OsobineNamena:     "MAXIMAL je gotovi krečnocementni malter, namenjen za mašinsko i ručno malterisanje svih nosivo sposobnih unutrašnjih zidnih površina. Može se koristiti kod svih vrsta zidova od cigle, opeke, gasbetonskih elemenata, betona i prirodnog kamena.",
			NacinRada:         "Površine moraju biti: suve, očišćene od prašine, masti i drugih nečistoća kao i slabo vezanih delova. Veće neravnine kao i rupe i šliceve od instalacija potrebno je prethodno ispuniti. Kod zidova koji su izrađeni ciglom, gde su fugne doboke i široke, iste je potrebno prethodno ispuniti pre malterisanja. Ovako pripremljene površine grundirati. Prilikom grundiranja glatkih površina, pre svega savetujemo upotrebu MAXIMAL Špric-a; druga preporuka je akrilni vezivni most MAXIKRIL Contact. Jako upojne površine grundirati MAXIKRIL Concentrate podlogom. Malter nanositi mašinski i odmah nakon toga grubo poravnati aluminijumskom „H“ letvom. Posle delimičnog sušenja vrši se odstranjivanje viška materijala. Malter se „otvara“ aluminijumskom „T“ letvom ili rešetkastim strugačem (rajbnom). Površina posle ove obrade ostaje gruba. Nakon „otvaranja“ površina se kvasi vodom i perdaši sunđerastom hoblom, čime se dobija fini konačni izgled. Minimalna debljina sloja je 1.5cm. Na neravnim površinama kod kojih je potrebno nanositi malter u debljem sloju, ponovo naneti malter sa pravljenjem pauze ali dok prethodni sloj još nije vezao. ",
			JedinicaPotrosnje: "kg/m² za 10mm debljine za ravne površine.",
			Potrosnja:         14,
			RokUpotrebe:       "6 meseci od datuma proizvodnje istaknutog na ambalaži. Čuvati u zatvorenoj i neoštećenoj ambalaži, u suvoj i provetrenoj prostoriji.",
			Jedinica:          "kg",
			Pakovanje:         25,
			Cena:              0.064,
			Slug:              "masinski_malter_rinfuz",
		},
		18: &model.WingMaterijal{
			Id:                19,
			Naziv:             "PK-kulir",
			Opis:              "PK-kulir",
			Obracun:           "Obračun po kilogrammu",
			Proizvodjac:       "",
			OsobineNamena:     "Dekorativni mozaični malter proizveden od višebojnog zrna mermera,izuzetno čvrst, vodootporan i postojan na svimatmosferskim prilikama.",
			NacinRada:         "Podlogu za nanošenjeprethodno dobro isušiti, očistiti i namazati PKakrilom. Dobro promešanu masu nanositi debljinom 50% većoj od veličine zrna.Zasušenu podlogu namazati ponovo. Nanošenje vršiti odozdo prema gore i dobro ravnjati tokom nanošenja kako bi se eliminisale nastale praznine između zrna.",
			JedinicaPotrosnje: "kg/m²",
			Potrosnja:         3.5,
			RokUpotrebe:       "12 meseci u originalnoj ambalaži skladišteno na suvom mestu, zaštiæeno od sunèeve svetlosti i smrzavanja. Datum proizvodnje i pakovanja utisnut na ambalaži.",
			Jedinica:          "kg",
			Pakovanje:         25,
			Cena:              0.75,
			Slug:              "pk_kulir",
		},
		19: &model.WingMaterijal{
			Id:                20,
			Naziv:             "PK AKRIL",
			Opis:              "PK AKRIL",
			Obracun:           "Obračun po kilogrammu",
			Proizvodjac:       "maxima",
			OsobineNamena:     "Akrilna strukturna podloganamenjena za ujednačavanje, neutralizaciju, učvršćivanje i vodoodbojnost podloge pre nanoše-nja akrilnih fasadnih boja i dekorativnih maletera.Preporučljivo je toniranje PK- Acryl podloge u istojnijansi kao završni sloj.",
			NacinRada:         "Podloga na koju se PK-Acrylnanosi mora biti čvrsta, èista, suva i bez ostataka ulja. PK-Acryl pre upotrebe promešati sa 15-20% vode.Tako razrednjenu podlogu nanositi na zid dugodlakim valjkom ili èetkom, u jednom sloju. Potrebno vreme za sušenje do nanošenja završnog sloja je 24h.",
			JedinicaPotrosnje: "kg/m²",
			Potrosnja:         0.25,
			RokUpotrebe:       "12 meseci u originalnoj ambalaži skladišteno na suvom mestu, zaštićeno od sunèeve svetlosti i smrzavanja. Datum proizvodnje i pakovanja utisnut na ambalaži.",
			Jedinica:          "kg",
			Pakovanje:         25,
			Cena:              0.73,
			Slug:              "pk_akril",
		},
		20: &model.WingMaterijal{
			Id:                21,
			Naziv:             "PK-PLAST",
			Opis:              "PK-PLAST",
			Obracun:           "Obračun po kilogrammu",
			Proizvodjac:       "pescar kolor",
			OsobineNamena:     "Visoko kvalitetan aktrilni malter velike cvrstoce I vodonepropustan. Lak za obradu I primenu. Otporan na UV zracenja I atmosferke prilike.",
			NacinRada:         "nanošenje: Priprema smese se vrsi dodavanjem male kolicine vode uz mesanje do potpune homogenizacije. Nanosi se celicnom cetkom – gletericom u debljini najkrupnijeg zrna. Povrsina na koju se nanosi mora biti cvrsta, cista, suva I premazana PK-Akryl podlogom. U zavisnosti od zeljene strukture malter se zatim obradjuje plasticnom gletericom I to: FULL struktura – odmah nakon nanosenja struktuirati kruzno; RAJB struktura – nakon nanosenja rajbovati kruznim pokretima do postizanja zeljene strukture.",
			JedinicaPotrosnje: "kg/m2",
			Potrosnja:         3,
			RokUpotrebe:       "12 meseci u originalnoj ambaazi skladisteno na suvom mestu, zasticeno od sunceve svetlosti I smrzavanja. Datum proizvodnje I rakovanja utisnut na ambalazi",
			Jedinica:          "kg",
			Pakovanje:         25,
			Cena:              0.58,
			Slug:              "pk_plast",
		},
		21: &model.WingMaterijal{
			Id:                22,
			Naziv:             "Lepak za kamen sivi",
			Opis:              "Lepak za kamen sivi",
			Obracun:           "Obračun po kilogrammu",
			Proizvodjac:       "rofix",
			OsobineNamena:     "Brzovezujući, beli, fleksibilni, tankoslojni lepak za visoke zahteve prema normi EN 12004 za postavljanje mermernih ploča i ploča od prirodnog kamena kao i drugih prirodnih ploča osetljivih na obojanje, na podu i zidu. Podesno u unutrašnjim i spoljašnjim područjima za estrih i podno grejanje. Za podove pod toplotnim opterećenjem, npr. na terasama, balkonima i na grejanim estrisima te u području saniranja kod lepljenja pločica na stare keramičke površine. Posebno podesno za svetle ploče i pločice. Zbog brzog vezanja potrebne vode za zamešavanje materijala može se smanjiti promena boje na površini svetlih ploča.",
			NacinRada:         "RÖFIX Lepak za keramiku naneti glatkom stranom zupčastog gletera na podlogu i sa nazubljenom stranom gletera pročešljati po mogućnosti u jednom smeru. Lepak naneti samo na onoliku površinu na koju je za vreme trajanja otvorenog vremena materijala moguće ugraditi obloge. Ukoliko se zahteva postavljanje pločica bez šupljina ispod pločica (u trajno vlažnim područjima), potrebno je raditi po metodi \"Floating- Buttering\". Lepak je podesan za obloge do veličine formata 60x60 cm. Na poleđinu obloga formata > 0,25 m² prethodno je potrebno ugraditi masu za poboljšanje prionjivosti. Ne koristiti materijal iz već otvorenih, starih pakovanja i ne mešati sa novim materijalom. Pločice se pomicanjem postavljaju u lepak, a njihov položaj se može ispraviti u propisanom roku za vreme postavljanja. ",
			JedinicaPotrosnje: "kg/m² zupčastim gleterom od 8 mm",
			Potrosnja:         3,
			RokUpotrebe:       "Skladištiti na suvom mestu (ako je moguće na drvenim paletama). Datum proizvodnje odštampan na vreći. Rok upotrebe najmanje 12 meseci prema direktivi 1907/2006/EZ na 20 °C, 65 % r.v.v. ",
			Jedinica:          "kg",
			Pakovanje:         25,
			Cena:              0.18,
			Slug:              "lepak_za_kamen_sivi",
		},
		22: &model.WingMaterijal{
			Id:                23,
			Naziv:             "PK-FAS",
			Opis:              "Fasadna boja",
			Obracun:           "Obračun po kilogramu",
			Proizvodjac:       "Pešar kolor",
			OsobineNamena:     "Koristi se za spoljašnju upotrebu, poseduje odliènu pokrivnu moæ i paropropusnost,otporna na suvo i vlažno brisanje. Bez mirisa. Može se tonirati u željene nijanse.",
			NacinRada:         "Priprema smese se vrši dodavanjem 15-20% vode uz mešanje do potpune homogenizacije. Površina na koju se boja nanosi mora biti čvrsta, čista, suva i impregnirana podlogom. Nanošenje se vrši valjkom u dva sloja ili pomoću kompresora. Drugi sloj se nanosi nakon potpunog sušenja prvog sloja.",
			JedinicaPotrosnje: "kg/m²",
			Potrosnja:         0.5,
			RokUpotrebe:       "12 meseci u originalnoj ambalaži skladišteno na suvom mestu, zaštićeno od sunèeve svetlosti i smrzavanja. Datum proizvodnje i pakovanja utisnut na ambalaži.",
			Jedinica:          "kg",
			Pakovanje:         25,
			Cena:              0.3,
			Slug:              "pk_fas",
		},
	}
}
